### ISSUE TITLE
[Bug] shadow 적용 문제

### ISSUE THREAD

**Issue by Rookie0031** [DeveloperAcademy-POSTECH/MC2-Team6-ECUBE#28]
<img width="985" alt="image" src="https://user-images.githubusercontent.com/103009135/172551153-528c9aa4-913c-42f4-81ab-05be76de833f.png">

 x축 방향 그림자가 잘리는 현상이 발생했습니다.

**Comment by jinccc97** [comment]
Vstack에 
.frame(maxWidth: .infinity)를 추가해보세요

**Comment by Rookie0031** [comment]
### 밀 부장님의 solution대로 해결했습니다

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/103009135/172555170-ab951fbc-e9fb-4223-8735-9d009b9f86dd.png">
