### ISSUE TITLE
Build error : FlowerView 내에 사용된 변수가 선언되지 않음 

### ISSUE THREAD

**Issue by Rookie0031** [DeveloperAcademy-POSTECH/MC2-Team6-ECUBE#47]
## flowerList 없음
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/103009135/173227227-71dae62b-b579-4428-85d4-d3087937e7e5.png">

## Flower 모델 없음 
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/103009135/173227250-81b8a130-dfad-4a21-be03-0187dd20f12b.png">

**Comment by jinccc97** [comment]
<img width="1512" alt="스크린샷 2022-06-12 오후 9 58 31" src="https://user-images.githubusercontent.com/61951603/173234419-8e42df99-b5f1-49e9-9313-728cb46a4dbd.png">

티모 이번 머지에서 해당 스트럭트들의 파일 삭제하신게 맞나요?

**Comment by teethemoji** [comment]
아뇨 밀리께서 리버트해주신 내용에 같이 빨려 들어갔나봅니다..
복구시켜두었어요
