### ISSUE TITLE
Build Issue : Color extension 

### ISSUE THREAD

**Issue by Rookie0031** [DeveloperAcademy-POSTECH/MC2-Team6-ECUBE#5]
# extension color로 Color 프로퍼티를 추가해도 반영되지 않는 현상

<img width="1221" alt="image" src="https://user-images.githubusercontent.com/103009135/172118362-ca9b8590-478b-4589-8d11-5b48e49db1a6.png">
이 부분에서 여기까지만 코드가 작성된게 맞나요? 제가 풀할때 뭔가 잘못된건가요??

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/103009135/172118431-25b922bc-5831-4696-a8a6-1cb9470bb976.png">

**Comment by Rookie0031** [comment]
<img width="1217" alt="image" src="https://user-images.githubusercontent.com/103009135/172127310-68eb73a7-1fc6-4dad-9244-c154b12ed9b8.png">

Asset을 바로 가져오면 error는 해결됨. extension이 왜 안되는지는 의문

**Comment by jinccc97** [comment]
<img width="1512" alt="스크린샷 2022-06-06 오후 7 17 44" src="https://user-images.githubusercontent.com/61951603/172142640-f1413bee-3c98-47e0-bb2a-43b7d3924a01.png">

colorExtension 파일이 app target에 안들어가 있었습니다. ㅋㅋㅋ 여기서 target Membership 체크만 넣어주면 됩니다..^^
